### ISSUE TITLE
[Question]OBS Color 

### ISSUE THREAD

**Issue by nidark** [Jire/Overwatcheat#158]
Hello,
I see the uage of OBS as a color-ban alternative.
How does this work ? Can OBS make a red -> magenta ?

Thank you!

**Comment by fooooooooooooooo** [comment]
if you get color banned (through sending mouse events or something) overwatch is just a black screen to most screen capture methods, but obs hooks into overwatch in a way that bypasses this. this means if you configure obs to capture overwatch, then you right click the source and make a fullscreen projector, you can configure this to capture the Fullscreen Projector window instead of ow, which bypasses the color ban
![image](https://user-images.githubusercontent.com/34515228/196746961-43512d99-b200-46ed-a4a9-e747d0135d2c.png)

**Comment by nidark** [comment]
Thanks. 
PS: I interpreted totaly differently ... :)
