### ISSUE TITLE
Aimbot always off the target by a fixed distance and only triggers on that point? 

### ISSUE THREAD

**Issue by vengefulcrop** [Jire/Overwatcheat#215]
For me the aimbot has a seemingly constant offset from the found target, and it will not react to a target that is near my crosshair either - it only reacts to it when I aim towards the bottom right and from there it is actually able to flick and track that specific point in relation to the target. I have read through similar issues, none of them were actually helpful. 
This is where I have to aim for it to react in any way and it is how far the tracking will be offset for me. I have tried messing with config values - no effect. I have tried setting the DPI scaling to a 100 percent as suggested in a different issue, did not work for me. My resolution is 1080p, the console says that its capturing at (896,476)
![photo_2023-01-12_02-35-38](https://user-images.githubusercontent.com/89088763/211955020-3323ec7c-7115-42c2-8fb3-e7a7049864e7.jpg)

**Comment by YanoGouarab** [comment]
This is because the aimbot is made for a 1040p resolution. you can to replace box_width and height wit these values, it will help. 
`# Generally 256x256 works well across most resolutions, although very high res (4K+) may need a bigger box.
box_width=320
box_height=180`

You'll may need to change the offset too, here are my settings : 
`# You can try playing around with this to change where to aim, like moving the y down to do bodyshots.1.18/1.13, y =.87
aim_offset_x=1.13
aim_offset_y=0.529`
